services:
  - type: web
    name: hadex-factory
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: ADMIN_PASSWORD
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: MAX_UPLOAD_MB
        value: "200"
